[package]
name = "transform"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
serde = "0.8.16"
toml = { version = "0.2.1", default-features = false, features = ["serde"] }
serde_json = "0.8.3"
serde_yaml = "0.5.0"
